name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker Image
        run: docker build --no-cache -t "${{ secrets.DOCKER_USERNAME }}"/url-shortener:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/url-shortener:latest
